settings:
  mp:
    pose:
      static_image_mode: False
      model_complexity: 1
      smooth_landmarks: True
      enable_segmentation: False
      smooth_segmentation: True
      min_detection_confidence: 0.5
      min_tracking_confidence: 0.5
    hands:
      static_image_mode: False
      model_complexity: 1
      min_detection_confidence: 0.5
      min_tracking_confidence: 0.5

  selected_marks:
    body: [0, 12, 14, 16, 11, 13, 15, 20, 28, 25, 27]
    body_v2:
      [
        "NOSE",
        "LEFT_SHOULDER",
        "LEFT_ELBOW",
        "LEFT_WRIST",
        "RIGHT_SHOULDER",
        "RIGHT_ELBOW",
        "RIGHT_WRIST",
        "LEFT_INDEX",
        "LEFT_ANKLE",
        "RIGHT_HIP",
        "RIGHT_KNEE",
      ]