settings:
  main_runner: "unity" # unity, debug, debug_quizz
  debug_organ: "heart" # heart, brain, liver, stomach, intestine, body

  adjust_orientation: True # If main runner is unity => True if mobile device used and False when using webcam
  enable_adjustments_settings: False # True or False
  override_typ_selected: True # Override the selected organ in unity if debug mode on

  err_distance: "error_distance" # send error message to current user if distance in not appropriate

  mp:
    pose:
      static_image_mode: False
      model_complexity: 1
      smooth_landmarks: True
      enable_segmentation: False
      smooth_segmentation: True
      min_detection_confidence: 0.5
      min_tracking_confidence: 0.5
    hands:
      static_image_mode: False
      model_complexity: 1
      min_detection_confidence: 0.5
      min_tracking_confidence: 0.5

  pose_landmarks:
    [
      "NOSE",
      "LEFT_EYE_INNER",
      "LEFT_EYE",
      "LEFT_EYE_OUTER",
      "RIGHT_EYE_INNER",
      "RIGHT_EYE",
      "RIGHT_EYE_OUTER",
      "LEFT_EAR",
      "RIGHT_EAR",
      "MOUTH_LEFT",
      "MOUTH_RIGHT",
      "LEFT_SHOULDER",
      "RIGHT_SHOULDER",
      "LEFT_ELBOW",
      "RIGHT_ELBOW",
      "LEFT_WRIST",
      "RIGHT_WRIST",
      "LEFT_PINKY",
      "RIGHT_PINKY",
      "LEFT_INDEX",
      "RIGHT_INDEX",
      "LEFT_THUMB",
      "RIGHT_THUMB",
      "LEFT_HIP",
      "RIGHT_HIP",
      "LEFT_KNEE",
      "RIGHT_KNEE",
      "LEFT_ANKLE",
      "RIGHT_ANKLE",
      "LEFT_HEEL",
      "RIGHT_HEEL",
      "LEFT_FOOT_INDEX",
      "RIGHT_FOOT_INDEX",
    ]

  selected_marks:
    body: [0, 12, 14, 16, 11, 13, 15, 20, 28, 25, 27]
    body_v2:
      [
        "NOSE",
        "LEFT_SHOULDER",
        "LEFT_ELBOW",
        "LEFT_WRIST",
        "RIGHT_SHOULDER",
        "RIGHT_ELBOW",
        "RIGHT_WRIST",
        "LEFT_INDEX",
        "LEFT_ANKLE",
        "RIGHT_HIP",
        "RIGHT_KNEE",
      ]