settings:
  main_runner: "debug" # unity, debug, debug_quizz
  debug_organ: "brain" # heart, brain, liver, stomach, intestine

  adjust_orientation: False # If main runner is unity => True if mobile device used and False when using webcam
  enable_adjustments_settings: False # True or False

  mp:
    pose:
      static_image_mode: False
      model_complexity: 1
      smooth_landmarks: True
      enable_segmentation: False
      smooth_segmentation: True
      min_detection_confidence: 0.5
      min_tracking_confidence: 0.5
    hands:
      static_image_mode: False
      model_complexity: 1
      min_detection_confidence: 0.5
      min_tracking_confidence: 0.5

  position:
    heart:
      command:
        x_offset: 0
        y_offset: -200
        z_offset: 0
      unity:
        x_offset: 0
        y_offset: -1.5
        z_offset: 15 

    brain:
      command:
        x_offset: 0
        y_offset: -50
        z_offset: 0
      unity:
        x_offset: 0
        y_offset: 1.2
        z_offset: 4

    liver:
      command:
        x_offset: -35
        y_offset: -150
        z_offset: 0
      unity:
        x_offset: -0.8
        y_offset: -2
        z_offset: 4

    stomach:
      command:
        x_offset: 30
        y_offset: -145
        z_offset: 0
      unity:
        x_offset: 0.85
        y_offset: -2.5
        z_offset: 4

    intestine:
      command:
        x_offset: 0
        y_offset: -100
        z_offset: 0
      unity:
        x_offset: 0
        y_offset: -2.8
        z_offset: 4

    body:
      command:
        x_offset: 0
        y_offset: 0
        z_offset: 0
      unity:
        x_offset: 0
        y_offset: 0
        z_offset: 0